### ISSUE TITLE
models @ dc42993

### ISSUE THREAD

**Issue by LiQiang0307** [yinguobing/arcface#1]
找不到models @ dc42993

**Comment by yinguobing** [comment]
我猜是git clone出了问题。请注意`models`是git submodule。

**Comment by LiQiang0307** [comment]
但是utils下的tfrecord_operator @ bdf7eaf是没问题的啊，这个models在github上打开是404啊

**Comment by yinguobing** [comment]
我明天去开发机上检查一下。有可能是submodule没有push上去。

**Comment by yinguobing** [comment]
@LiQiang0307  submodule已经更新，我在本机试了下应该没问题。你有时间再试一下吧。

**Comment by LiQiang0307** [comment]
好的，非常感谢！这回应该好用了！！！谢谢！

**Comment by yinguobing** [comment]
客气了，应该是我感谢你，帮我发现了这个错误，谢谢 ❤️

**Comment by yinguobing** [comment]
This issue seems to be resolved. Plrease reopen it if not.
