### ISSUE TITLE
您好！请问下第一个epoch loss一直在30左右，正常吗？

### ISSUE THREAD

**Issue by gitlabspy** [yinguobing/arcface#2]
loss 在前一个epoch收敛很慢

**Comment by yinguobing** [comment]
一个完整的epoch吗？应该不至于，你看下accuracy有没有提升的趋势。

**Comment by gitlabspy** [comment]
是的，0.5很难收敛，后面都在20上下波动，换0.35就可以收敛到很小，verification太慢了没测 😂，主要是觉得loss不收敛就没测。

**Comment by yinguobing** [comment]
这里的0.5和0.35是指学习率？accuracy在训练log里有的，也可以在TensorBoard中查看。

**Comment by gitlabspy** [comment]
抱歉没描述清楚，0.5 和0.3 都是arcface loss的margin

**Comment by yinguobing** [comment]
你这么说提醒了我，这个margin我一直使用默认值没有改动过。另外，一开始的学习率可以大一些。代码默认0.001是我后期使用的数值。你可以参考下作者在论文里使用过的数值。

如果还是不收敛，换到resnet分支试一下。我发现ResNet收敛比HRNet更快一点。

**Comment by gitlabspy** [comment]
好的，感谢！

**Comment by yangzishy** [comment]
> 你这么说提醒了我，这个margin我一直使用默认值没有改动过。另外，一开始的学习率可以大一些。代码默认0.001是我后期使用的数值。你可以参考下作者在论文里使用过的数值。
> 
> 如果还是不收敛，换到resnet分支试一下。我发现ResNet收敛比HRNet更快一点。

改了学习率也不收敛   而且准确率accuracy稳定在百分之二十多   不会提升了  这是什么情况
